### ISSUE TITLE
[prettier 적용] Prettier 적용 세팅

### ISSUE THREAD

**Issue by Derek-94** [dev-floor/untitled-client#20]
### 상세 내용

- 기존에 적용되지 않던 `prettier` 적용 관련 이슈.
- `package.json` 의 `script.format` 에 불필요한 single quotation 발견.

### 진행 중인 작업

- [x] `.prettier` 파일 수정 
- [x] 전체 파일 prettier 적용.

**Comment by hyunju95** [comment]
확인완료했습니다~!
